# Generated by Django 5.0 on 2026-02-12 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['staff', 'admin']}, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
